# Generated by Django 5.1.7 on 2025-03-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='pexels-fotios-photos-1092644.jpg', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
