# Generated by Django 5.1.7 on 2025-03-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image/test2.png', null=True, upload_to='photos/%y/%m/%d'),
        ),
    ]
