# Generated by Django 5.1.6 on 2025-03-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
